### ISSUE TITLE
Playground not responsive

### ISSUE THREAD

**Issue by tobimori** [getkirby/kql.getkirby.com#3]
While being unlikely that the playground is accessed and actually used by someone on their mobile phone, it should support a basic responsive layout where the code windows are aligned in rows rather than columns, if there's not enough space.

**Comment by distantnative** [comment]
I thought about this when updating the playground. But it would still remain pretty much unusable on mobile. So I'm not sure if it makes sense

**Comment by tobimori** [comment]
I'd see the examples as something I can use on mobile whilst stumbling across the site when exploring GitHub etc.

Nobody will due large editing but if the examples work it's fine I guess.

**Comment by bastianallgeier** [comment]
It's not the most beautiful responsive version in the world but at least it works.
